/**
 * Generate Tailwind v4 Theme from @prism/tokens
 *
 * This script converts our TypeScript design tokens into CSS custom properties
 * that Tailwind v4 can consume via the @theme directive.
 *
 * Why this approach?
 * - Single source of truth: @prism/tokens (TypeScript)
 * - Tailwind v4 uses CSS-first configuration
 * - This script bridges the two systems
 * - Tokens remain type-safe and shareable across packages
 */

import { colors, spacing, typography } from "@prism/tokens";
import { writeFileSync } from "fs";
import { join } from "path";

function generateThemeCSS(): string {
  let css = `/**
 * Prism Design System - Tailwind Theme
 *
 * Auto-generated from @prism/tokens
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * To modify theme values, edit packages/tokens/src/*
 * Then run: pnpm generate:theme
 */

@import "tailwindcss";

@theme {
`;

  // Generate color variables
  css += `  /* Primary Colors */\n`;
  Object.entries(colors.primary).forEach(([key, value]) => {
    css += `  --color-primary-${key}: ${value};\n`;
  });

  css += `\n  /* Neutral Colors */\n`;
  Object.entries(colors.neutral).forEach(([key, value]) => {
    css += `  --color-neutral-${key}: ${value};\n`;
  });

  css += `\n  /* Semantic Colors - Success */\n`;
  Object.entries(colors.success).forEach(([key, value]) => {
    css += `  --color-success-${key}: ${value};\n`;
  });

  css += `\n  /* Semantic Colors - Error */\n`;
  Object.entries(colors.error).forEach(([key, value]) => {
    css += `  --color-error-${key}: ${value};\n`;
  });

  css += `\n  /* Semantic Colors - Warning */\n`;
  Object.entries(colors.warning).forEach(([key, value]) => {
    css += `  --color-warning-${key}: ${value};\n`;
  });

  css += `\n  /* Semantic Colors - Info */\n`;
  Object.entries(colors.info).forEach(([key, value]) => {
    css += `  --color-info-${key}: ${value};\n`;
  });

  // Generate spacing variables
  css += `\n  /* Spacing Scale (4px base) */\n`;
  Object.entries(spacing).forEach(([key, value]) => {
    css += `  --spacing-${key}: ${value};\n`;
  });

  // Generate typography variables - font sizes
  css += `\n  /* Font Sizes */\n`;
  Object.entries(typography.fontSize).forEach(([key, value]) => {
    css += `  --font-size-${key}: ${value};\n`;
  });

  // Generate typography variables - font weights
  css += `\n  /* Font Weights */\n`;
  Object.entries(typography.fontWeight).forEach(([key, value]) => {
    css += `  --font-weight-${key}: ${value};\n`;
  });

  // Generate typography variables - line heights
  css += `\n  /* Line Heights */\n`;
  Object.entries(typography.lineHeight).forEach(([key, value]) => {
    css += `  --line-height-${key}: ${value};\n`;
  });

  css += `}\n`;

  return css;
}

// Generate and write the theme file
const themeCSS = generateThemeCSS();
const outputPath = join(__dirname, "..", "src", "styles", "theme.css");

writeFileSync(outputPath, themeCSS, "utf-8");

console.log("✅ Generated theme.css from @prism/tokens");
console.log(`📝 Output: ${outputPath}`);
